### ISSUE TITLE
Messed Up Over Time

### ISSUE THREAD

**Issue by MichaelM04** [ImagicalCorp/InstantRespawn#2]
Great plugin but i noticed that if you die sometimes your stuck to where you have to quit or use /spawn (the respawn time was set to 1 Sec) also it kills sometimes even when you didn't die minor bugs and not sure where to start with fixing these issues

**Comment by thebigsmileXD** [comment]
I am sure thats not the fault of my plugin. 
Seems more like your server is overloaded

**Comment by thebigsmileXD** [comment]
Any errors in the console?

**Comment by InfornoFire** [comment]
lol, uhh, this is the work of pocketmine and imagicalmine

**Comment by thebigsmileXD** [comment]
@InfornoFire its not.
I made this plugin all myself. 

@MichaelM04
Are you sure you set that up correctly?

**Comment by InfornoFire** [comment]
aka, Its a glitch in the builds, seriously, its on the issue tracker on ImagicalMine, its not the plugin, or something he did wrong, its a glitch with your builds, the plugin is useless without a fix

**Comment by thebigsmileXD** [comment]
In the latest IM-code? Yea, i think Mr piggy messes it up.

**Comment by MichaelM04** [comment]
I don't know I'll try again to see if its working with pocketmine official or ImagicalMine

**Comment by thebigsmileXD** [comment]
Works on 1.5 api like a charm

**Comment by InfornoFire** [comment]
Confirmed
