### ISSUE TITLE
The world doesnt exists!

### ISSUE THREAD

**Issue by RocoWayne** [ImagicalCorp/InstantRespawn#4]
Hi! Im testing InstantRespawn and when i try to add a world the plugin says "The world NAME doesnt exist, chec case NAME mus be a valid ManyWorld-World"

Whats is the problem?

**Comment by thebigsmileXD** [comment]
Yes, saw the same bug some days ago. You have to load the world first

**Comment by RocoWayne** [comment]
I try loading the world: /mw load LEVELNAME

And when i try to /instanterespawn add LEVELNAME this error appear

11.01 07:31:17 [Server] Server thread/WARNING InvalidArgumentException: "array_keys() expects parameter 1 to be array, string given" (E_WARNING) in "/InstantRespawn_v0.3.2.phar/src/thebigsmileXD/InstantRespawn/Main" at line 184
11.01 07:31:17 [Server] Server thread/CRITICAL Unhandled exception executing command 'instantrespawn add Gaturro' in instantrespawn: array_keys() expects parameter 1 to be array, string given

**Comment by thebigsmileXD** [comment]
Yea its a bug since 0.13

I reported the bug some daYs ago

**Comment by RocoWayne** [comment]
Oh, i see... can wait for the fix then!

**Comment by RocoWayne** [comment]
any news man?

**Comment by RocoWayne** [comment]
:(

**Comment by thebigsmileXD** [comment]
should be fixed in my local version, update soon at https://github.com/thebigsmileXD/InstantRespawn
